import { Scholarship, Grade, Prefecture, Major } from './types';

export const SCHOLARSHIP_DATA: Scholarship[] = [
  {
    id: 1,
    name: "DAISO財団",
    provider: "DAISO財団",
    type: "給付型",
    amount_per_year: 600000,
    eligible_grades: [Grade.University1, Grade.University2, Grade.University3],
    eligible_prefs: [],
    eligible_majors: [],
    income_requirement: "経済的困窮",
    other_requirements: "20歳までの学生",
    deadline: "2025-05-31",
    url: "https://daiso-zaidan.or.jp/recruiting/"
  },
  {
    id: 2,
    name: "池森財団",
    provider: "池森財団",
    type: "給付型",
    amount_per_year: 242000,
    eligible_grades: [Grade.HighSchool1, Grade.HighSchool2, Grade.HighSchool3],
    eligible_prefs: [],
    eligible_majors: [],
    income_requirement: "経済的困窮",
    other_requirements: "高校生対象",
    deadline: "2025-06-15",
    url: "https://ikemorizaidan.fancl.jp/scholarship.html"
  },
  {
    id: 3,
    name: "キーエンス財団",
    provider: "キーエンス財団",
    type: "給付型",
    amount_per_year: 1200000,
    eligible_grades: [],
    eligible_prefs: [],
    eligible_majors: [],
    income_requirement: "経済的困窮",
    other_requirements: "学業優秀",
    deadline: "2025-04-20",
    url: "https://www.keyence-foundation.or.jp/elements/pdf/2026/application_requirements_2065_01.pdf"
  },
  {
    id: 4,
    name: "ソニー",
    provider: "ソニーグループ",
    type: "給付型",
    amount_per_year: 1200000,
    eligible_grades: [],
    eligible_prefs: [],
    eligible_majors: [Major.Engineering, Major.NaturalSciences],
    income_requirement: "指定なし",
    other_requirements: "理工系学部志望",
    deadline: "2025-06-30",
    url: "https://www.sony.com/ja/SonyInfo/diversity/steam-ex/"
  },
  {
    id: 5,
    name: "電通育英会",
    provider: "電通育英会",
    type: "給付型",
    amount_per_year: 960000,
    eligible_grades: [],
    eligible_prefs: [],
    eligible_majors: [],
    income_requirement: "経済的困窮",
    other_requirements: "入学一時金30万あり",
    deadline: "2025-07-10",
    url: "https://www.dentsu-ikueikai.or.jp/scholarship/"
  },
  {
    id: 6,
    name: "似鳥国際奨学財団",
    provider: "似鳥国際奨学財団",
    type: "給付型",
    amount_per_year: 840000,
    eligible_grades: [],
    eligible_prefs: [],
    eligible_majors: [],
    income_requirement: "経済的困窮",
    other_requirements: "学業優秀",
    deadline: "2025-05-25",
    url: "https://www.nitori-shougakuzaidan.com/"
  },
  {
    id: 7,
    name: "守谷育英会",
    provider: "守谷育英会",
    type: "給付型",
    amount_per_year: 1260000,
    eligible_grades: [Grade.HighSchool1, Grade.HighSchool2, Grade.HighSchool3, Grade.University1, Grade.University2, Grade.University3, Grade.University4],
    eligible_prefs: [],
    eligible_majors: [],
    income_requirement: "経済的困窮",
    other_requirements: "高校生から院生まで対象",
    deadline: "2025-04-30",
    url: "https://moritani-scholarship.or.jp/scholarship/"
  },
  {
    id: 8,
    name: "木下記念事業団",
    provider: "木下記念事業団",
    type: "給付型",
    amount_per_year: 960000,
    eligible_grades: [],
    eligible_prefs: [],
    eligible_majors: [],
    income_requirement: "経済的困窮",
    other_requirements: "学業優秀",
    deadline: "2025-06-01",
    url: "https://kinoshita-kinen.or.jp/" // Placeholder
  },
  {
    id: 9,
    name: "地域育成財団",
    provider: "地域育成財団",
    type: "給付型",
    amount_per_year: 360000,
    eligible_grades: [],
    eligible_prefs: [],
    eligible_majors: [],
    income_requirement: "指定なし",
    other_requirements: "地方創生に興味のある学生",
    deadline: "2025-07-20",
    url: "https://chiiki-ikusei.com/scheduled"
  },
  {
    id: 10,
    name: "コカ・コーラ奨学生",
    provider: "コカ・コーラ教育・環境財団",
    type: "給付型",
    amount_per_year: 240000,
    eligible_grades: [],
    eligible_prefs: [],
    eligible_majors: [],
    income_requirement: "経済的困窮",
    other_requirements: "学業優秀",
    deadline: "2025-05-15",
    url: "https://www.cocacola-zaidan.jp/edu-support/pdf/edu-support2026_01.pdf"
  },
  {
    id: 11,
    name: "三菱UFJ信託奨学",
    provider: "三菱UFJ信託奨学財団",
    type: "給付型",
    amount_per_year: 875000,
    eligible_grades: [Grade.University2, Grade.University3, Grade.University4],
    eligible_prefs: [],
    eligible_majors: [],
    income_requirement: "経済的困窮",
    other_requirements: "大学2年生以上対象",
    deadline: "2025-04-10",
    url: "https://www.scholarship.or.jp/program/"
  },
  {
    id: 12,
    name: "G-7奨学財団",
    provider: "G-7奨学財団",
    type: "給付型",
    amount_per_year: 1200000,
    eligible_grades: [Grade.University1, Grade.University2, Grade.University3, Grade.University4],
    eligible_prefs: [],
    eligible_majors: [],
    income_requirement: "経済的困窮",
    other_requirements: "大学生対象",
    deadline: "2025-06-20",
    url: "https://g-7foundation.or.jp/syougaku.html"
  },
  {
    id: 13,
    name: "日揮・実吉奨学会",
    provider: "日揮・実吉奨学会",
    type: "給付型",
    amount_per_year: 400000,
    eligible_grades: [],
    eligible_prefs: [],
    eligible_majors: [],
    income_requirement: "経済的困窮",
    other_requirements: "指定大学在学中",
    deadline: "2025-04-25",
    url: "https://www.jgcs.or.jp/business/found.html"
  },
  {
    id: 14,
    name: "TCS奨学生",
    provider: "TCS奨学財団",
    type: "給付型",
    amount_per_year: 600000,
    eligible_grades: [Grade.University3, Grade.University4],
    eligible_prefs: [],
    eligible_majors: [],
    income_requirement: "経済的困窮",
    other_requirements: "学部3年生、院1年生対象",
    deadline: "2025-05-30",
    url: "https://tcs-foundation.or.jp/scholarship_student/index.html"
  },
  {
    id: 15,
    name: "業務スーパージャパンドリーム財団",
    provider: "業務スーパージャパンドリーム財団",
    type: "給付型",
    amount_per_year: 2100000,
    eligible_grades: [],
    eligible_prefs: [],
    eligible_majors: [],
    income_requirement: "所得制限あり",
    other_requirements: "海外への留学意欲があること",
    deadline: "2025-01-15",
    url: "https://www.kobebussan.or.jp/pdf/guideline_202501_02.pdf?20251017-1403"
  },
  {
    id: 16,
    name: "JDC未来財団奨学",
    provider: "JDC未来財団",
    type: "給付型",
    amount_per_year: 240000,
    eligible_grades: [Grade.HighSchool1, Grade.HighSchool2, Grade.HighSchool3],
    eligible_prefs: [],
    eligible_majors: [Major.Engineering, Major.NaturalSciences, Major.SocialSciences],
    income_requirement: "経済的困窮",
    other_requirements: "理学・工学・農学系",
    deadline: "2025-06-10",
    url: "https://www.jdc-miraizaidan.or.jp/guide/shougakukin.html"
  },
  {
    id: 17,
    name: "リクルートスカラシップ",
    provider: "リクルート財団",
    type: "給付型",
    amount_per_year: 1000000,
    eligible_grades: [],
    eligible_prefs: [],
    eligible_majors: [],
    income_requirement: "経済的困窮",
    other_requirements: "年収制限あり",
    deadline: "2025-10-15",
    url: "https://www.recruit-foundation.org/scholarship/academic2025"
  },
  {
    id: 18,
    name: "柳井正財団",
    provider: "柳井正財団",
    type: "給付型",
    amount_per_year: 7000000,
    eligible_grades: [],
    eligible_prefs: [],
    eligible_majors: [],
    income_requirement: "所得制限あり",
    other_requirements: "米国・英国の大学への進学者対象。授業料、生活費等を含む。",
    deadline: "2025-01-08",
    url: "https://www.yanaitadashi-foundation.or.jp/application/"
  },
  {
    id: 19,
    name: "トビタテ!留学JAPAN",
    provider: "文部科学省",
    type: "給付型",
    amount_per_year: 3000000,
    eligible_grades: [],
    eligible_prefs: [],
    eligible_majors: [],
    income_requirement: "経済的困窮",
    other_requirements: "海外大学への進学・留学",
    deadline: "2025-02-28",
    url: "https://tobitate-mext.jasso.go.jp/news/detail.html?id=493"
  },
  {
    id: 20,
    name: "ナガワひまわり財団",
    provider: "ナガワひまわり財団",
    type: "給付型",
    amount_per_year: 500000,
    eligible_grades: [],
    eligible_prefs: [],
    eligible_majors: [],
    income_requirement: "経済的困窮",
    other_requirements: "女性・地方出身者",
    deadline: "2025-05-20",
    url: "https://www.nagawa-himawari.or.jp/" // Placeholder
  },
  {
    id: 21,
    name: "紺碧の空奨学金",
    provider: "早稲田大学",
    type: "給付型",
    amount_per_year: 625000,
    eligible_grades: [Grade.HighSchool3],
    eligible_prefs: [],
    eligible_majors: [],
    income_requirement: "経済的困窮",
    other_requirements: "児童養護施設出身者で、早稲田大学を目指す学生",
    deadline: "2025-01-20",
    url: "https://www.waseda.jp/inst/scholarship/" // Placeholder
  },
  {
    id: 22,
    name: "早稲田大学めざせ！都の西北奨学金",
    provider: "早稲田大学",
    type: "給付型",
    amount_per_year: 700000,
    eligible_grades: [Grade.HighSchool3],
    eligible_prefs: [Prefecture.Other],
    eligible_majors: [],
    income_requirement: "経済的困窮",
    other_requirements: "首都圏外出身の学生",
    deadline: "2025-01-20",
    url: "https://www.waseda.jp/inst/scholarship/aid/undergraduate/" // Placeholder
  },
  {
    id: 23,
    name: "慶應義塾大学独自の奨学金",
    provider: "慶應義塾大学",
    type: "給付型",
    amount_per_year: 600000,
    eligible_grades: [],
    eligible_prefs: [],
    eligible_majors: [],
    income_requirement: "経済的困窮",
    other_requirements: "学業優秀かつ経済的困難な学生",
    deadline: "2025-04-10",
    url: "https://www.keio.ac.jp/ja/student-life/scholarships/" // Placeholder
  },
  {
    id: 24,
    name: "地の塩・世の光奨学金",
    provider: "全国児童養護施設協議会",
    type: "給付型",
    amount_per_year: 360000,
    eligible_grades: [],
    eligible_prefs: [],
    eligible_majors: [],
    income_requirement: "経済的困窮",
    other_requirements: "児童養護施設出身者対象、予約型給付制度",
    deadline: "2025-06-25",
    url: "https://www.zen-yo-kyo.jp/p_4_2.html" // Placeholder
  },
  {
    id: 25,
    name: "上智大学新入生奨学金",
    provider: "上智大学",
    type: "給付型",
    amount_per_year: 500000,
    eligible_grades: [Grade.HighSchool3],
    eligible_prefs: [],
    eligible_majors: [],
    income_requirement: "家計困難",
    other_requirements: "家計が困難な新入生対象",
    deadline: "2025-02-15",
    url: "https://www.sophia.ac.jp/jpn/studentlife/scholarship/sgs_new.html" // Placeholder
  }
];
